version: '3'

volumes:
  pg_data:
  media:
  static:
  frontend_build:

services:

  db:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

  backend:
    image: vladislavrotvash/sefer_backend:latest
    env_file: .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "make project-init-prod-in-container"
    volumes:
      - media:/app/transcribe_app/media
      - static:/app/transcribe_app/collected_static

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - frontend_build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/

  frontend:
    env_file: .env
    image: acunathink/sefer_frontend
    volumes:
      - frontend_build:/app/result_build/

