# Generated by Django 4.2.1 on 2023-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textblock",
            options={
                "verbose_name": "text_block",
                "verbose_name_plural": "text_blocks",
            },
        ),
        migrations.AddConstraint(
            model_name="textblock",
            constraint=models.UniqueConstraint(
                fields=("minute", "text", "transcription"),
                name="uniq_transcriptions_text_block",
            ),
        ),
    ]
