# Generated by Django 4.2.1 on 2024-04-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="keywords",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Ключевое слово"
            ),
        ),
        migrations.AlterField(
            model_name="personalities",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Персоналия"
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="audio_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Backet_url_name"
            ),
        ),
    ]
