# Generated by Django 4.2.1 on 2024-06-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="transcription/audio",
                verbose_name="Аудио",
            ),
        ),
    ]
