# Generated by Django 4.2.1 on 2024-09-08 05:54

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="редактор",
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="cities",
            field=models.ManyToManyField(
                blank=True, to="transcription.city", verbose_name="Города"
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="countries",
            field=models.ManyToManyField(
                blank=True, to="transcription.country", verbose_name="Страны"
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, to="transcription.keywords", verbose_name="Ключевые слова"
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="personalities",
            field=models.ManyToManyField(
                blank=True, to="transcription.personalities", verbose_name="Персоналии"
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="transcription",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_blocks",
                to="transcription.transcription",
            ),
        ),
        migrations.AddField(
            model_name="personalities",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="редактор",
            ),
        ),
        migrations.AddField(
            model_name="keywords",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="редактор",
            ),
        ),
        migrations.AddField(
            model_name="keywords",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transcription.keywords",
                verbose_name="Категория/Подкатегория",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="редактор",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cities",
                to="transcription.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="редактор",
            ),
        ),
    ]
