# Generated by Django 4.2.1 on 2024-08-16 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="textblock",
            name="uniq_transcriptions_text_block",
        ),
    ]
