# Generated by Django 4.2.1 on 2024-05-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0002_alter_city_name_alter_keywords_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Страна"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "confirmed",
                    models.BooleanField(default=True, verbose_name="Подтверждено?"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("modern", "Современное"),
                            ("historical", "Историческое"),
                        ],
                        default="modern",
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Место", "verbose_name_plural": "Места"},
        ),
        migrations.AddField(
            model_name="city",
            name="confirmed",
            field=models.BooleanField(default=True, verbose_name="Подтверждено?"),
        ),
        migrations.AddField(
            model_name="keywords",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AddField(
            model_name="keywords",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Ключевое слово (англ.)",
            ),
        ),
        migrations.AddField(
            model_name="personalities",
            name="is_confirmed",
            field=models.BooleanField(default=True, verbose_name="Подтверждено"),
        ),
        migrations.AddField(
            model_name="personalities",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AddField(
            model_name="personalities",
            name="name_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Имя (англ.)",
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="code",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Шифр"
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обновление"
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="transcription_status",
            field=models.CharField(
                choices=[
                    ("not_sent", "Не отправлено"),
                    ("sent", "Отправлено"),
                    ("received", "Готово"),
                ],
                default="not_sent",
                max_length=20,
                verbose_name="Статус расшифровки",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Место"),
        ),
        migrations.AlterField(
            model_name="keywords",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Ключевое слово (рус.)"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cities",
                to="transcription.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="countries",
            field=models.ManyToManyField(
                blank=True, to="transcription.country", verbose_name="Страны"
            ),
        ),
    ]
