# Generated by Django 4.2.1 on 2023-06-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0002_transcription_delete_trancription"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minute", models.PositiveIntegerField(verbose_name="Minute")),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textblock",
                        to="transcription.transcription",
                    ),
                ),
            ],
        ),
    ]
