# Generated by Django 4.2.1 on 2023-06-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0002_alter_textblock_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transcription",
            options={
                "verbose_name": "Транскрипция",
                "verbose_name_plural": "Транскрипции",
            },
        ),
        migrations.AddField(
            model_name="textblock",
            name="keywords",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ключевые слова."
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="personalities",
            field=models.TextField(blank=True, null=True, verbose_name="Персоналии"),
        ),
        migrations.AddField(
            model_name="transcription",
            name="name",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="textblock",
            name="transcription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_blocks",
                to="transcription.transcription",
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="audio",
            field=models.FileField(
                upload_to="transcription/audio", verbose_name="Аудио"
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="audio_url",
            field=models.URLField(blank=True, verbose_name="Backet_url_name"),
        ),
    ]
