# Generated by Django 4.2.1 on 2024-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0003_remove_textblock_uniq_transcriptions_text_block"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transcription",
            options={
                "verbose_name": "Каталог записей",
                "verbose_name_plural": "Каталоги записей",
            },
        ),
        migrations.AddField(
            model_name="transcription",
            name="time_total",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Длительность аудио"
            ),
            preserve_default=False,
        ),
    ]
