# Generated by Django 4.2.1 on 2023-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcription",
            "0003_alter_transcription_options_textblock_keywords_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textblock",
            options={
                "verbose_name": "Текстовый_блок",
                "verbose_name_plural": "Текстовые_блоки",
            },
        ),
        migrations.AlterField(
            model_name="textblock",
            name="minute",
            field=models.PositiveIntegerField(verbose_name="Минута"),
        ),
        migrations.AlterField(
            model_name="textblock",
            name="text",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="name",
            field=models.CharField(max_length=60, verbose_name="Название"),
        ),
    ]
