# Generated by Django 4.2.1 on 2024-06-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0003_transcription_audio_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcription",
            name="audio_url",
        ),
        migrations.AlterField(
            model_name="textblock",
            name="transcription",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_blocks",
                to="transcription.transcription",
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="audio",
            field=models.FileField(
                default="default_image.jpg",
                upload_to="transcription/audio",
                verbose_name="Аудио",
            ),
        ),
    ]
