# Generated by Django 4.2.1 on 2023-06-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0003_textblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textblock",
            name="transcription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="textblocks",
                to="transcription.transcription",
            ),
        ),
    ]
