# Generated by Django 4.2.1 on 2024-06-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0004_remove_transcription_audio_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="transcription/audio",
                verbose_name="Аудио",
            ),
        ),
    ]
