# Generated by Django 4.2.1 on 2023-08-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcription",
            "0004_alter_textblock_options_alter_textblock_minute_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textblock",
            options={
                "verbose_name": "Текстовый блок",
                "verbose_name_plural": "Текстовые блоки",
            },
        ),
        migrations.AlterField(
            model_name="textblock",
            name="transcription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_blocks",
                to="transcription.transcription",
            ),
        ),
    ]
