# Generated by Django 4.2.1 on 2023-08-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0005_alter_textblock_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Город")),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Personalities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Персоналия")),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Персоналия",
                "verbose_name_plural": "Персоналии",
            },
        ),
        migrations.RemoveField(
            model_name="textblock",
            name="personalities",
        ),
        migrations.AddField(
            model_name="textblock",
            name="cities",
            field=models.ManyToManyField(
                blank=True, null=True, to="transcription.city", verbose_name="Города"
            ),
        ),
        migrations.AddField(
            model_name="textblock",
            name="personalities",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="transcription.personalities",
                verbose_name="Персоналии",
            ),
        ),
    ]
