# Generated by Django 4.2.1 on 2023-08-30 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcription",
            "0006_city_personalities_remove_textblock_personalities_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textblock",
            options={
                "verbose_name": "Текстовый_блок",
                "verbose_name_plural": "Текстовые_блоки",
            },
        ),
    ]
