# Generated by Django 4.2.1 on 2023-08-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0008_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="keywords",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transcription.keywords",
                verbose_name="родитель",
            ),
        ),
        migrations.AlterField(
            model_name="keywords",
            name="name",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Персоналия"
            ),
            preserve_default=False,
        ),
    ]
