# Generated by Django 4.2.1 on 2023-09-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0010_alter_keywords_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textblock",
            name="keywords",
        ),
        migrations.AddField(
            model_name="textblock",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="transcription.keywords",
                verbose_name="Ключевые слова",
            ),
        ),
    ]
